[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Image Filter Library"
authors = [{name = "nnyongiii", email = "nayoung225@hanyang.ac.kr"}]
dynamic = ["version", "description"]